version: 0.0
os: linux
files:
  - source: /TMAN_CounterWebApp.zip
    destination: /opt/tomcat/webapps
hooks:
  BeforeInstall:
    - location: scripts/shutdown.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/startup.sh
      timeout: 300
      runas: root
