version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/CounterWebApp.war
    - TMAN_CounterWebApp_$(date +%Y-%m-%d).war
  discard-paths: yes
